Use "Message" property of Exception
jellyfin/SQLitePCL.pretty.netstandard pull request #4
Opened 2019-06-15 13:15 UTC by ilexius

Use "Message" property of Exception class to display message. Otherwise the message is not displayed in the VS NUnit test runner

2019-06-19 04:50 UTC, cvium commented
I don't think we're really interested in maintaining this ourselves. This fork is mostly just to get a netstandard package on nuget.

2019-06-20 18:37 UTC, Bond-009 approved these changes

2019-08-11 10:14 UTC, Bond-009 requested changes
This small change is fine, as we will need to release a new version of this anyway if we want to update this to SQLitePCLRaw 2.0.

2019-08-11 10:14 UTC, Bond-009 commented on SQLitePCL.pretty/SQLiteException.cs
> +            $"{ErrorCode}: {Message}\r\n{base.ToString()}";
```suggestion
            $"{ErrorCode}: {base.ToString()}";
```
The base class already displays the message.

2019-08-13 11:23 UTC, Bond-009 approved these changes

2019-08-13 12:59 UTC, merged